language:
    - cpp

compiler:
    - gcc

before_script:
  - sudo apt-get update -qq
  - sudo apt-get install libboost-dev
  - sudo apt-get install libopenblas-dev

script:
    - cd projects/Linux
    - git clone https://github.com/acuoci/OpenSMOKEpp.git
    - hg clone https://bitbucket.org/eigen/eigen/
    - wget http://heanet.dl.sourceforge.net/project/rapidxml/rapidxml/rapidxml%201.13/rapidxml-1.13.zip
    - unzip rapidxml-1.13.zip
    - pwd
    - ls
    - aclocal
    - automake --add-missing
    - ./configure CXX=g++ --enable-openmp=no --with-opensmoke=OpenSMOKEpp --with-eigen=eigen --with-rapidxml=rapidxml-1.13
    - make all

